from __future__ import annotations

MEMBERSHIP_STATUS_PENDING = "PENDING"
MEMBERSHIP_STATUS_ACTIVE = "ACTIVE"
MEMBERSHIP_STATUS_REJECTED = "REJECTED"
MEMBERSHIP_STATUS_EXITED = "EXITED"
MEMBERSHIP_STATUS_REMOVED = "REMOVED"

MEMBERSHIP_STATUSES = {
    MEMBERSHIP_STATUS_PENDING,
    MEMBERSHIP_STATUS_ACTIVE,
    MEMBERSHIP_STATUS_REJECTED,
    MEMBERSHIP_STATUS_EXITED,
    MEMBERSHIP_STATUS_REMOVED,
}

JOIN_SOURCE_APPLY = "APPLY"
JOIN_SOURCE_DIRECT = "DIRECT"
JOIN_SOURCE_IMPORT = "IMPORT"
JOIN_SOURCES = {JOIN_SOURCE_APPLY, JOIN_SOURCE_DIRECT, JOIN_SOURCE_IMPORT}

# CONFLICT-C9: 数据库文档使用 APPLY/DIRECT/IMPORT，接口文档示例使用
# APPLICATION/INVITE/INVITED。保守策略以数据库文档为准。
JOIN_SOURCE_API_VALUES = {
    JOIN_SOURCE_APPLY: "APPLY",
    JOIN_SOURCE_DIRECT: "DIRECT",
    JOIN_SOURCE_IMPORT: "IMPORT",
}

MEMBERSHIP_TRANSITIONS = {
    "apply": {
        None: MEMBERSHIP_STATUS_PENDING,
        MEMBERSHIP_STATUS_REJECTED: MEMBERSHIP_STATUS_PENDING,
        MEMBERSHIP_STATUS_EXITED: MEMBERSHIP_STATUS_PENDING,
        MEMBERSHIP_STATUS_REMOVED: MEMBERSHIP_STATUS_PENDING,
    },
    "direct_add": {None: MEMBERSHIP_STATUS_ACTIVE},
    "approve": {MEMBERSHIP_STATUS_PENDING: MEMBERSHIP_STATUS_ACTIVE},
    "reject": {MEMBERSHIP_STATUS_PENDING: MEMBERSHIP_STATUS_REJECTED},
    "exit": {MEMBERSHIP_STATUS_ACTIVE: MEMBERSHIP_STATUS_EXITED},
    "remove": {MEMBERSHIP_STATUS_ACTIVE: MEMBERSHIP_STATUS_REMOVED},
}

BLOCK_TYPE_UNFINISHED_ASSIGNMENT = "unfinished_assignment"
BLOCK_TYPE_ACTIVE_INSTANCE = "active_instance"
BLOCK_TYPE_UNDER_REVIEW = "under_review"
BLOCK_TYPE_ARCHIVE = "archive"
BLOCK_TYPE_DESTROY = "destroy"

EXIT_BLOCKING_ASSIGNMENT_STATUSES = {
    "ASSIGNED",
    "PROVISIONING",
    "RUNNING",
    "SUBMITTED",
    "UNDER_REVIEW",
}
REMOVE_BLOCKING_ASSIGNMENT_STATUSES = {"PROVISIONING", "RUNNING", "SUBMITTED"}

EVENT_MEMBERSHIP_APPLIED = "membership.applied"
EVENT_MEMBERSHIP_APPROVED = "membership.approved"
EVENT_MEMBERSHIP_REJECTED = "membership.rejected"
EVENT_MEMBERSHIP_ADDED = "membership.added"
EVENT_MEMBERSHIP_EXITED = "membership.exited"
EVENT_MEMBERSHIP_REMOVED = "membership.removed"
EVENT_SESSION_REVOCATION_REQUESTED = "workspace.session.revocation.requested"

MEMBERSHIP_TOPIC = "membership.events"
SESSION_TOPIC = "workspace.session.events"
AGGREGATE_TYPE_MEMBERSHIP = "MEMBERSHIP"
AGGREGATE_TYPE_SESSION = "SESSION"
