"""Platform-wide Server-Sent Events types and processing stages."""

from enum import StrEnum


class SSEEventType(StrEnum):
    OPERATION_STEP_UPDATED = "OPERATION_STEP_UPDATED"
    OPERATION_COMPLETED = "OPERATION_COMPLETED"
    OPERATION_FAILED = "OPERATION_FAILED"
    OPERATION_CANCELLED = "OPERATION_CANCELLED"
    RESOURCE_STATE_CHANGED = "RESOURCE_STATE_CHANGED"
    RECORD_SUBMITTED = "RECORD_SUBMITTED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    ARCHIVE_COMPLETED = "ARCHIVE_COMPLETED"
    ACCESS_REVOKED = "ACCESS_REVOKED"
    QUOTA_CHANGED = "QUOTA_CHANGED"
    TASK_WITHDRAWN = "TASK_WITHDRAWN"


class SSEStage(StrEnum):
    VALIDATION = "VALIDATION"
    PREPARATION = "PREPARATION"
    EXECUTION = "EXECUTION"
    HEALTH_CHECK = "HEALTH_CHECK"
    SNAPSHOT = "SNAPSHOT"
    REVIEW = "REVIEW"
    ARCHIVE = "ARCHIVE"
    ACCESS = "ACCESS"
    CLEANUP = "CLEANUP"
    QUOTA = "QUOTA"
