[SERVICE]
    Flush                     2
    Daemon                    Off
    Log_Level                 info
    Parsers_File              parsers.conf
    storage.path              /buffers
    storage.sync              normal
    storage.backlog.mem_limit 32M

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    storage.type      filesystem

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       json
    Reserve_Data True
    Preserve_Key False

[FILTER]
    Name   lua
    Match  *
    script /fluent-bit/etc/redact.lua
    call   redact

[OUTPUT]
    Name          http
    Match         *
    Host          log-ingest
    Port          8081
    URI           /logs
    Format        json_lines
    Retry_Limit   False
    storage.total_limit_size 256M
